"""
Django settings for payment_service project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# RabbitMQ Configuration
RABBITMQ = {
    "HOST": os.getenv("RABBITMQ_HOST", "localhost"),
    "PORT": int(os.getenv("RABBITMQ_PORT", 5672)),
    "USER": os.getenv("RABBITMQ_USER", "ishimwe"),
    "PASS": os.getenv("RABBITMQ_PASS", ""),
    "VHOST": os.getenv("RABBITMQ_VHOST", "microservice_one"),
    "QUEUE": os.getenv("RABBITMQ_QUEUE", "microservice_one.events"),
}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition
INSTALLED_APPS = [
    # ASGI
    "daphne",
    "channels",
    
    # Minimal Django core (REQUIRED)
    "django.contrib.contenttypes",
    "django.contrib.staticfiles",

    # Third-party
    "corsheaders",
    "rest_framework",

    # Your apps
    "src.infrastructure.apps.outbox",
    'src.infrastructure.apps.eventstore',
    'src.infrastructure.apps.payment',
    'src.infrastructure.apps.idempontence',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "payment_service.middleware.auth.JWTAuthenticationMiddleware",
    "src.application.idempotency.middleware.IdempotencyMiddleware",
]

ROOT_URLCONF = 'payment_service.urls'

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "formatters": {
        "simple": {
            "format": "[{levelname}] {message}",
            "style": "{",
        },
    },
    "loggers": {
        # Root logger
        "": {
            "handlers": ["console"],
            "level": os.getenv('LOG_LEVEL', 'INFO'),
        },
    },
}

# Channel Layers Configuration
CHANNEL_LAYER_HOSTS = os.getenv('CHANNEL_LAYER_HOSTS', '127.0.0.1:6379').split(',')
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [tuple(host.split(':')) for host in CHANNEL_LAYER_HOSTS],
            "capacity": int(os.getenv('CHANNEL_LAYER_CAPACITY', 1000)),
            "expiry": int(os.getenv('CHANNEL_LAYER_EXPIRY', 10)),
        },
    },
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'payment_service.wsgi.application'


# Database Configuration
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("POSTGRES_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.getenv("POSTGRES_DB", "paymentdb"),
        "USER": os.getenv("POSTGRES_USER", "ishimwe"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", ""),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = os.getenv('DJANGO_LANGUAGE_CODE', 'en-us')
TIME_ZONE = os.getenv('DJANGO_TIME_ZONE', 'UTC')
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security Settings
INTERNAL_API_KEY = os.getenv("INTERNAL_API_KEY")
SERVICE_JWT = os.getenv("SERVICE_JWT")
AUTH_SERVICE_URL = os.getenv("AUTH_SERVICE_URL", "http://127.0.0.1:8000/zedvye_one/")
AUTH_PUBLIC_KEY_URL = os.getenv("AUTH_PUBLIC_KEY_URL", "http://127.0.0.1:8000/zedvye_one/users/public_key/")

# Additional Production Security Settings (commented but recommended)
"""
# Uncomment these for production:
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
"""