apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.appname" (dict "ctx" $ "svc" "payment") }}
  labels:
    app: {{ include "helm.appname" (dict "ctx" $ "svc" "payment") }}
spec:
  selector:
    app: {{ include "helm.appname" (dict "ctx" $ "svc" "payment") }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.payment.port }}
      targetPort: {{ .Values.backend.payment.port }}
  type: ClusterIP