# Generated by Django 5.2.6 on 2026-01-08 14:22

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReadModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique payment identifier', primary_key=True, serialize=False)),
                ('wallet_id', models.UUIDField(help_text='UUID of the associated wallet', verbose_name='wallet ID')),
                ('user_id', models.UUIDField(help_text='UUID of the user who initiated the payment', verbose_name='user ID')),
                ('amount', models.DecimalField(decimal_places=4, help_text='Payment amount (always positive)', max_digits=19, verbose_name='amount')),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code (e.g., USD, EUR) in uppercase', max_length=3, verbose_name='currency')),
                ('payment_type', models.CharField(choices=[('DEPOSIT', 'deposit'), ('WITHDRAWAL', 'withdrawal'), ('PAYMENT', 'payment'), ('REFUND', 'refund'), ('ADJUSTMENT', 'adjustment')], help_text='Type of payment: deposit, withdrawal, payment, refund, or adjustment', max_length=20, verbose_name='payment type')),
                ('payment_method', models.CharField(choices=[('WALLET', 'wallet'), ('CREDIT_CARD', 'credit_card'), ('BANK_TRANSFER', 'bank_transfer'), ('PAYPAL', 'paypal'), ('OTHER', 'other')], help_text='Method used for the payment', max_length=20, verbose_name='payment method')),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('PROCESSING', 'processing'), ('SUCCEEDED', 'succeeded'), ('FAILED', 'failed'), ('CANCELLED', 'cancelled'), ('REFUNDED', 'refunded')], default='PENDING', help_text='Current lifecycle status of the payment', max_length=20, verbose_name='status')),
                ('reference_id', models.UUIDField(blank=True, help_text='Optional reference to related entity (e.g., booking_id, original payment_id)', null=True, verbose_name='reference ID')),
                ('description', models.TextField(blank=True, help_text='Human-readable description or failure reason', null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'payment read model',
                'verbose_name_plural': 'payment read models',
                'db_table': 'payment_read_model',
                'indexes': [models.Index(fields=['wallet_id'], name='idx_payment_read_wallet'), models.Index(fields=['user_id'], name='idx_payment_read_user'), models.Index(fields=['status'], name='idx_payment_read_status'), models.Index(fields=['payment_type'], name='idx_payment_read_type'), models.Index(fields=['reference_id'], name='idx_payment_read_reference'), models.Index(fields=['created_at'], name='idx_payment_read_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='check_payment_amount_positive')],
            },
        ),
    ]
