# Generated by Django 5.2.6 on 2026-01-09 07:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('idempotency_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='idempotency ID')),
                ('key', models.CharField(help_text='Client-provided unique idempotency key', max_length=255, verbose_name='idempotency key')),
                ('user_id', models.UUIDField(help_text='UUID of the user initiating the request', verbose_name='user ID')),
                ('fingerprint', models.CharField(help_text='Canonical SHA-256 hash of the request payload', max_length=64, verbose_name='request fingerprint')),
                ('expires_at', models.DateTimeField(help_text='Timestamp after which this key is considered expired', verbose_name='expires at')),
                ('status', models.CharField(choices=[('PENDING', 1), ('COMPLETED', 2), ('FAILED', 3)], default='PENDING', help_text='Current lifecycle state of the idempotency key', max_length=20, verbose_name='status')),
                ('response_data', models.JSONField(blank=True, help_text='Serialized StoredResponse: {status_code, headers, body}', null=True, verbose_name='response data')),
                ('request_id', models.UUIDField(blank=True, help_text='Original HTTP request UUID', null=True, verbose_name='request ID')),
                ('correlation_id', models.UUIDField(blank=True, help_text='Distributed tracing correlation ID', null=True, verbose_name='correlation ID')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Lease expiration time for processing lock', null=True, verbose_name='locked until')),
                ('locked_by', models.CharField(blank=True, help_text='Identifier of the worker/pod holding the lock', max_length=255, null=True, verbose_name='locked by')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('request_method', models.CharField(blank=True, help_text='HTTP verb (e.g., POST, PUT)', max_length=10, null=True, verbose_name='request method')),
                ('request_path', models.CharField(blank=True, help_text='API endpoint path', max_length=255, null=True, verbose_name='request path')),
                ('client_ip', models.GenericIPAddressField(blank=True, help_text='Originating client IP address', null=True, verbose_name='client IP')),
            ],
            options={
                'verbose_name': 'idempotency key',
                'verbose_name_plural': 'idempotency keys',
                'db_table': 'idempotency_keys',
                'indexes': [models.Index(fields=['key', 'user_id'], name='idx_key_user'), models.Index(fields=['user_id', 'status'], name='idx_user_status'), models.Index(fields=['fingerprint'], name='idx_fingerprint'), models.Index(fields=['expires_at'], name='idx_expires_at'), models.Index(fields=['locked_until'], name='idx_locked_until'), models.Index(fields=['created_at'], name='idx_created_at')],
                'constraints': [models.UniqueConstraint(fields=('key', 'user_id'), name='unique_key_per_user'), models.CheckConstraint(condition=models.Q(('status__in', ['COMPLETED', 'FAILED']), models.Q(('locked_by__isnull', True), ('locked_until__isnull', True)), models.Q(models.Q(('locked_until__isnull', True), _negated=True), models.Q(('locked_by__isnull', True), _negated=True)), _connector='OR'), name='check_lock_only_on_pending')],
            },
        ),
    ]
