apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.appname" (dict "ctx" $ "svc" "payment") }}
  labels:
    app: {{ include "helm.appname" (dict "ctx" $ "svc" "payment") }}
    app.kubernetes.io/component: payment-service
type: Opaque
stringData:
  # Django
  DJANGO_SECRET_KEY: {{ .Values.config.payment.djangoSecretKey | default "django-insecure-change-me-in-prod" | quote }}

  # Auth & Security
  INTERNAL_API_KEY: {{ .Values.config.payment.internalApiKey | default "change-me" | quote }}
  SERVICE_JWT: {{ .Values.config.payment.serviceJwt | default "change-me" | quote }}
